### ISSUE TITLE
Query server for `entity`

### ISSUE THREAD

**Issue by naomijub** [naomijub/gXTDB#18]
As a User
I want to be able to query XTDB for `entity`
So I need support for entity query https://docs.xtdb.com/clients/1.23.2/clojure/#_entity
https://docs.xtdb.com/clients/http/#entity

Acceptance Criteria:

* Server supports entity query

**Comment by pfeodrippe** [comment]
I guess I will give a try on this issue to understand the project a little bit better and see if there are any dependencies or if it's good to go o/ 

As a heads-up, I will be traveling next week, but I will try to make some onboarding this week, exciting project, Naome!

**Comment by pfeodrippe** [comment]
Oops, *Naome não, it was a typo, sorry. Naomi 🤗

**Comment by naomijub** [comment]
I have seen so much worst than Naome 😂 (Noemi for ex)

**Comment by pfeodrippe** [comment]
> I have seen so much worst than Naome 😂 (Noemi for ex)

haeuaehuaheuauheueh yeah, but I really knew/know your name, sorry again. People love to call me Paolo ahhaeuaheuahue

**Comment by pfeodrippe** [comment]
@naomijub When fetching the document, converting it to a Struct would be lossy as this protobuf type follows JSON's rules (while EDN has more data types).

I see that you created a EDN serde for Rust, do we want to use that here? As gXTDB is supposed to be used in other environments than Rust, I think, instead, we would not like to use something like 1) transit or 2) encoding general EDN inside gXTDB protos.

What do you think? Maybe “2” is already possible with protojure? 

“1” would require yet another library to parse things, maybe “2” or another alternative would be the way to go.

A third option would be to be lossy.

**Comment by naomijub** [comment]
2 would be cool, maybe check if there is any open issue in protojure that can relate to this. If there is end type needed in rust, I can manage that from tonic/rust side by having the protos

**Comment by pfeodrippe** [comment]
> @pfeodrippe https://www.reddit.com/r/Clojure/comments/8fxypv/edn_and_protocol_buffer/?utm_source=share&utm_medium=ios_app&utm_name=ioscss&utm_content=1&utm_term=1
> 
> Might be of help

Thanks, it is! Will start to go deeper when I’m back from my travel o/ Exciting work ahead

**Comment by pfeodrippe** [comment]
@naomijub Now I have some time again and have been able to see your changes, so it seems that you have added `EntityTx` already, thank you!! 

I see that we are returning the content hash only (not the content yet), so I would continue with option `2` here to add the content, is that correct?

**Comment by naomijub** [comment]
I added [entity-tx](https://docs.xtdb.com/clients/1.23.2/http/#entity-tx), but there is another query called [entity](https://docs.xtdb.com/clients/1.23.2/http/#entity). They return quite different information:
<img width="996" alt="Captura de Tela 2023-06-26 às 12 13 32 AM" src="https://github.com/naomijub/gXTDB/assets/14813660/03d99dfc-0bb0-4dda-b350-1942cb6fb125">

But they are very similar in behaviour

**Comment by pfeodrippe** [comment]
> @pfeodrippe I added [entity-tx (http ref)](https://docs.xtdb.com/clients/1.23.2/http/#entity-tx), but there is another query called [entity (http ref)](https://docs.xtdb.com/clients/1.23.2/http/#entity). They return quite different information: <img alt="Captura de Tela 2023-06-26 às 12 13 32 AM" width="996" src="https://user-images.githubusercontent.com/14813660/248670827-03d99dfc-0bb0-4dda-b350-1942cb6fb125.png">
> 
> But they are very similar in behaviour

Oh missed that, thanks!!

**Comment by pfeodrippe** [comment]
@naomijub This protobuf limitation of keys being only strings or integers really sucks, maybe we should be constrained by that or should we go with the transit path? I’m willing to go with the last, wdyt?

**Comment by pfeodrippe** [comment]
> @naomijub This protobuf limitation of keys being only strings or integers really sucks, maybe we should be constrained by that or should we go with the transit path? I’m willing to go with the last, wdyt?



> @naomijub This protobuf limitation of keys being only strings or integers really sucks, maybe we should be constrained by that or should we go with the transit path? I’m willing to go with the last, wdyt?

We already have yours edn-rs, why not transit-rs? Ahahahahaha

**Comment by naomijub** [comment]
> > @naomijub This protobuf limitation of keys being only strings or integers really sucks, maybe we should be constrained by that or should we go with the transit path? I’m willing to go with the last, wdyt?
> 
> 
> We already have yours edn-rs, why not transit-rs? Ahahahahaha

I would first use string, then in a new PR experiment with transit. Wdyt?

**Comment by pfeodrippe** [comment]
> > > @naomijub This protobuf limitation of keys being only strings or integers really sucks, maybe we should be constrained by that or should we go with the transit path? I’m willing to go with the last, wdyt?
> > 
> > 
> > We already have yours edn-rs, why not transit-rs? Ahahahahaha
> 
> I would first use string, then in a new PR experiment with transit. Wdyt?

Sure o/ Thanks

**Comment by pfeodrippe** [comment]
Just to clarify, you mean the contents being returned as strings or the keys of all maps as strings? i'm thinking that's the first \o

**Comment by naomijub** [comment]
> Just to clarify, you mean the contents being returned as strings or the keys of all maps as strings? i'm thinking that's the first \o

Th content

Currently the keys are parsed to protojure keys as strings
