### ISSUE TITLE
Add reasoning for the project

### ISSUE THREAD

**Issue by pfeodrippe** [naomijub/gXTDB#23]
Would like to know more about the reasoning for the project, @naomijub's story.

It can be just a one-liner, just to understand the use cases you had in mind :D

**Comment by naomijub** [comment]
The first reasoning is that XTDB is a powerful time serial database, in my opinion, it might be even more interesting that Datomic. However, XDTB, when it started had limited support for HTTP ([Transistor](https://github.com/naomijub/transistor) crate for when it was called Crux), but had enough.

The objective of this project is to enable a high performance (gRPC) and low level client (Rust), with a language that can be easily used to generate multiple other clients, similarly to what is done in [BRcode](https://github.com/naomijub/brcode).

Did it answer your question?

**Comment by pfeodrippe** [comment]
Oh yeah, thanks, Naomi! o/
